### ISSUE TITLE
チャンネル画面実装 1

### ISSUE THREAD

**Issue by ryotarolab** [ryotarolab/TYPICA#6]
### 概要

チャンネル画面実装

* ワイヤーの画面は以下に格納
https://drive.google.com/drive/u/0/folders/0B0fsu2p7ZstuQk1JbGpLSVlueW8

### 機能仕様

*

**Comment by ryotarolab** [comment]
@kumabook 
そもそも、サイドメニューから他の画面に切り替えるにはどうすれば良い？
MenuTableViewControllerでセルをタップしたデリゲートつけて、MiniPlayerViewControllerでcenterPanelを切り替える？？

**Comment by ryotarolab** [comment]
あ、できました。
``self.sidePanelController.centerPanel = ViewController``
でいけた。

**Comment by kumabook** [comment]
そうっすね。

https://github.com/kumabook/MusicFav/blob/master/MusicFav/MiniPlayerViewController.swift#L65

を参考に。

**Comment by ryotarolab** [comment]
@kumabook 
MusicFavの場合のように、MiniPlayerViewController はAppDelegateのクラスのプロパティにすべき？
https://github.com/kumabook/MusicFav/blob/master/MusicFav/AppDelegate.swift

**Comment by ryotarolab** [comment]
残りは　#25 でやる。
